# Autostart
exec-once = waybar
exec-once = awww-daemon
exec-once = greenclip daemon
exec-once = hypridle
exec-once = swaync
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = nm-applet
exec-once = blueman-applet
# Set Themes and Appearance
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-mocha-mauve-standard+default"
exec-once = gsettings set org.gnome.desktop.interface icon-theme "Adwaita"
exec-once = gsettings set org.gnome.desktop.interface cursor-theme "default"
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
