#!/usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#	Author	-	gh0stzk
#	Repo	-	https://github.com/gh0stzk/dotfiles
#	Copyright (C) 2021-2024 gh0stzk <z0mbi3.zk@protonmail.com>

# Current rice
read -r RICETHEME <"${HOME}"/.config/bspwm/.rice

# Set environment variables
export PATH="$HOME/.config/bspwm/src:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

# Get the number of connected monitors
monitor_count=$(xrandr -q | grep -w 'connected' | wc -l)

# Initialize workspace counter
count=1

# If there are two monitors, assign 5 workspaces to each, else 10 to the single monitor
if [ "$monitor_count" -eq 2 ]; then
	for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
		bspc monitor "$monitor" -d '1' '2' '3' '4' '5'
	done
elif [ "$monitor_count" -eq 1 ]; then
	# Assign 10 workspaces to the single monitor
	# Loop through all outputs listed by xrandr
	for output in $(xrandr | grep 'disconnected' | cut -d' ' -f1); do
		xrandr --output "$output" --off
	done
	RelocateDesktop &
	single_monitor=$(xrandr -q | grep -w 'connected' | cut -d' ' -f1)
	bspc monitor "$single_monitor" -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'
fi

# Default 1 monitor with 6 workspaces
# for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
# 	count += 1
# 	bspc monitor "$monitor" -d '1' '2' '3' '4' '5' #bspc monitor "$monitor" -d '' '' '' '' '' ''
# done

## For two or three monitors configuration see https://github.com/gh0stzk/dotfiles/wiki/Two-or-more-monitors-setup

#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝

bspc config external_rules_command "${HOME}"/.config/bspwm/src/ExternalRules

bspc config window_gap 5
bspc config split_ratio 0.51
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 5
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a scratch sticky=on state=floating focus=on

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

# Set system vars for polybar
"$HOME"/.config/bspwm/src/SetSysVars

# Launch sxhkd daemon
pidof -q sxhkd || { sxhkd -c "${HOME}"/.config/bspwm/src/config/sxhkdrc & }

# Launch picom
pidof -q picom || { picom --config "${HOME}"/.config/bspwm/src/config/picom.conf & }

# Load current theme
"${HOME}"/.config/bspwm/rices/"${RICETHEME}"/Theme.sh

# Launch xsettingsd
pidof -q xsettings || { xsettingsd --config="${HOME}"/.config/bspwm/src/config/xsettingsd >/dev/null 2>&1 & }

# Launch eww daemon
pidof -q eww || { eww -c "${HOME}"/.config/bspwm/eww daemon & }

# Launch clipboard daemon
pidof -q greenclip || { greenclip daemon & }

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# End one time code

# Launch nm-applet
pidof -q nm-applet || nm-applet &
