# Catppuccin Theme Definition

# Hyprland
HYPR_ACTIVE_BORDER="rgba(cba6f7ee) rgba(f5c2e7ee) 45deg"
HYPR_INACTIVE_BORDER="rgba(45475aee)"

# Waybar
WAYBAR_BACKGROUND="#1e1e2e"
WAYBAR_FOREGROUND="#cdd6f4"
WAYBAR_PRIMARY="#cba6f7"
WAYBAR_SECONDARY="#45475a"
WAYBAR_ALERT="#f38ba8"
WAYBAR_SUCCESS="#a6e3a1"

# Kitty
KITTY_BACKGROUND="#1e1e2e"
KITTY_FOREGROUND="#cdd6f4"
KITTY_CURSOR="#cdd6f4"
KITTY_SELECTION_BACKGROUND="#cdd6f4"
KITTY_SELECTION_FOREGROUND="#1e1e2e"
