#!/bin/bash

THEME=$1
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
THEMES_DIR="$SCRIPT_DIR/../themes"

if [ -z "$THEME" ]; then
  echo "Available themes:"
  ls "$THEMES_DIR" | sed 's/\.sh//'
  exit 0
fi

THEME_FILE="$THEMES_DIR/$THEME.sh"

if [ ! -f "$THEME_FILE" ]; then
  echo "Error: Theme '$THEME' not found."
  exit 1
fi

source "$THEME_FILE"

echo "Applying theme: $THEME..."

# --- Update Configuration Files ---

cat >"$HOME/.config/colors.json" <<EOF
{
  "background": "$WAYBAR_BACKGROUND",
  "foreground": "$WAYBAR_FOREGROUND",
  "primary": "$WAYBAR_PRIMARY",
  "secondary": "$WAYBAR_SECONDARY",
  "alert": "$WAYBAR_ALERT",
  "success": "$WAYBAR_SUCCESS"
}
EOF

cat >"$HOME/.config/hypr/colors.conf" <<EOF
\$active_border_col = $HYPR_ACTIVE_BORDER
\$inactive_border_col = $HYPR_INACTIVE_BORDER
EOF

cat >"$HOME/.config/waybar/colors.css" <<EOF
@define-color background $WAYBAR_BACKGROUND;
@define-color foreground $WAYBAR_FOREGROUND;
@define-color primary $WAYBAR_PRIMARY;
@define-color secondary $WAYBAR_SECONDARY;
@define-color alert $WAYBAR_ALERT;
@define-color success $WAYBAR_SUCCESS;
EOF

cat >"$HOME/.config/kitty/current-theme.conf" <<EOF
background $KITTY_BACKGROUND
foreground $KITTY_FOREGROUND
cursor $KITTY_CURSOR
selection_background $KITTY_SELECTION_BACKGROUND
selection_foreground $KITTY_SELECTION_FOREGROUND
EOF

cat >"$HOME/.config/tmux/tmux-theme.conf" <<EOF
# Generated by theme_switcher.sh

set -g message-style "fg=$WAYBAR_BACKGROUND,bg=$WAYBAR_PRIMARY,bold"

set -g pane-border-style "fg=$WAYBAR_SECONDARY"
set -g pane-active-border-style "fg=$WAYBAR_PRIMARY"

set -g status-fg "$WAYBAR_FOREGROUND"
set -g status-bg "$WAYBAR_BACKGROUND"

set -g mode-style "fg=$WAYBAR_BACKGROUND,bg=$WAYBAR_PRIMARY"

set -g clock-mode-colour "$WAYBAR_PRIMARY"

set -g status-style "fg=$WAYBAR_FOREGROUND,bg=$WAYBAR_BACKGROUND"

set -g window-status-style "fg=$WAYBAR_FOREGROUND,bg=$WAYBAR_BACKGROUND"
set -g window-status-activity-style "bg=$WAYBAR_BACKGROUND,fg=$WAYBAR_SECONDARY"
set -g window-status-current-style "fg=$WAYBAR_BACKGROUND,bg=$WAYBAR_ALERT"

set -g status-left-style none
set -g status-right-style none

set -g status-right "#[fg=$WAYBAR_PRIMARY]#[fg=$WAYBAR_BACKGROUND,bg=$WAYBAR_PRIMARY] #[fg=$WAYBAR_FOREGROUND,bg=$WAYBAR_SECONDARY] #W #[fg=$WAYBAR_PRIMARY]#[fg=$WAYBAR_BACKGROUND,bg=$WAYBAR_PRIMARY] #[fg=$WAYBAR_FOREGROUND,bg=$WAYBAR_SECONDARY] #{p:pane_current_path} #[fg=$WAYBAR_SUCCESS]#[fg=$WAYBAR_BACKGROUND,bg=$WAYBAR_SUCCESS] #[fg=$WAYBAR_FOREGROUND,bg=$WAYBAR_SECONDARY] #S "

set -g window-status-separator "#[bg=$WAYBAR_BACKGROUND] "
set -g window-status-current-format "#[fg=$WAYBAR_FOREGROUND,bg=$WAYBAR_SECONDARY] #W #[fg=$WAYBAR_BACKGROUND,bg=$WAYBAR_PRIMARY] #I#[fg=$WAYBAR_PRIMARY,bg=$WAYBAR_BACKGROUND]"
set -g window-status-format "#[fg=$WAYBAR_SECONDARY,bg=$WAYBAR_BACKGROUND] #W #[fg=$WAYBAR_BACKGROUND,bg=$WAYBAR_SECONDARY] #I#[fg=$WAYBAR_SECONDARY,bg=$WAYBAR_BACKGROUND]"
EOF

# --- Reload Components ---

pkill waybar || true
waybar &
disown

tmux source-file ~/.config/tmux/tmux.conf || true

notify-send "Theme Changed" "Applied theme: $THEME"

echo "Theme '$THEME' applied successfully."
